#-------------------------------
# General Site Settings
title: Osman Perviz
logo: # You can add own logo. For example '/images/logo.png'.
description: Osman Perviz's personal blog, a software engineer currently living in Germany.
baseurl: "/osman_perviz_dot_com" # the subpath of your site, e.g. /blog
url: "https://osmanperviz.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Osman Perviz
  bio: I'm a software engineer with experience translating business requirements and objectives into fully-realized solutions.
  avatar: '/images/OsiBosi.jpg'

social:
- {icon: "ion-logo-twitter", label: Twitter, link: "https://twitter.com/osmanperviz"}
- {icon: "ion-logo-facebook", label: Facebook, link: "https://facebook.com"}
- {icon: "ion-logo-linkedin", label: Linkedin, link: "https://linkedin.com/in/osman-perviz"}
- {icon: "ion-logo-github", label: Linkedin, link: "https://github.com/osmanperviz"}


# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Hey, I’m Osman! Software Engineer.
  hero__description: I'm a software engineer with experience translating business requirements and objectives into fully-realized solutions.
  hero__image: '/images/OsiBosi02.jpg'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: true # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Get interesting news # Add your Title
mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Join # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: osmanperviz@gmail.com # Add your email for contact form
  description: If you want to contact me, feel free to fill in the form below and I will get back to you as soon as possible. # Add a description of your form

# NOTE
# Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed